"use client";

import { useMemo, useState } from "react";
import { AlertCircle, MapPin, Package, Search } from "lucide-react";

import { getParcelByTrackingId, mockParcels } from "@/lib/mockData";
import { fetchParcelFromPublicApi } from "@/lib/publicApi";

import { ParcelTimeline } from "@/components/ParcelTimeline";
import { DelayPredictionCard } from "@/components/DelayPredictionCard";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export function TrackClient({ initialTrackingId }: { initialTrackingId?: string }) {
  const defaultId = mockParcels[0]?.trackingId ?? "";
  const seeded = (initialTrackingId?.trim() || defaultId).toUpperCase();

  const [trackingId, setTrackingId] = useState(seeded);
  const [submitted, setSubmitted] = useState(seeded);

  const parcel = useMemo(() => {
    const base = getParcelByTrackingId(submitted);
    if (base) return base;
    // Public API integration: external clients provide tracking_id only.
    return fetchParcelFromPublicApi(submitted);
  }, [submitted]);

  return (
    <div className="mx-auto w-full max-w-6xl px-4 py-10">
      <div className="flex flex-col gap-2 daksh-fade-in">
        <div className="daksh-kicker">Citizen Tracking Interface</div>
        <h1 className="text-2xl font-semibold tracking-tight">Parcel Tracking</h1>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Enter an article tracking ID to view scan events, DIGIPIN codes, and the predicted delay window.
        </p>
      </div>

      <Card className="mt-6 daksh-glass daksh-elevated daksh-transition">
        <CardHeader>
          <CardTitle className="text-base">Tracking Lookup</CardTitle>
        </CardHeader>
        <CardContent>
          <form
            className="flex flex-col gap-3 sm:flex-row"
            onSubmit={(e) => {
              e.preventDefault();
              setSubmitted(trackingId);
            }}
          >
            <div className="flex-1">
              <Input
                value={trackingId}
                onChange={(e) => setTrackingId(e.target.value)}
                placeholder="Example: IPXK9A72IN"
                aria-label="Tracking ID"
                className="daksh-focus-ring"
              />
              <div className="mt-2 text-xs text-muted-foreground">
                Demo IDs: <span className="daksh-code font-medium">IPXK9A72IN</span>,{" "}
                <span className="daksh-code font-medium">RPL7Q2D1IN</span>
                <span className="hidden sm:inline">
                  {" "}
                  • External clients can open{" "}
                  <span className="daksh-code font-medium">/track?tracking_id=XXXX</span>
                </span>
              </div>
            </div>
            <Button type="submit" className="bg-primary hover:bg-primary/90 daksh-elevated daksh-focus-ring">
              <Search className="mr-2 h-4 w-4" />
              Track
            </Button>
          </form>
        </CardContent>
      </Card>

      {!parcel ? (
        <div className="mt-6 daksh-fade-in">
          <Alert className="daksh-glass daksh-elevated">
            <AlertCircle className="h-4 w-4" />
            <AlertTitle>Article not located</AlertTitle>
            <AlertDescription className="leading-relaxed">
              No scan record is available for the provided ID in this demo dataset. Use one of the listed demo IDs, or open tracking using a valid <span className="daksh-code font-medium">tracking_id</span> generated by an integrating client.
            </AlertDescription>
          </Alert>
        </div>
      ) : (
        <div className="mt-6 grid gap-6 lg:grid-cols-3 daksh-slide-up">
          <div className="space-y-6 lg:col-span-2">
            <Alert className="border-primary/20 bg-primary/5 daksh-glass daksh-elevated daksh-transition">
              <AlertCircle className="h-4 w-4 text-primary" />
              <AlertTitle className="text-primary">Operational Signal Detected</AlertTitle>
              <AlertDescription className="mt-1">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div>
                    <div className="font-medium text-foreground">{parcel.proactiveAlert.title}</div>
                    <div className="text-sm text-muted-foreground leading-relaxed">{parcel.proactiveAlert.message}</div>
                  </div>
                  <Badge
                    variant={
                      parcel.proactiveAlert.severity === "High"
                        ? "destructive"
                        : parcel.proactiveAlert.severity === "Medium"
                          ? "default"
                          : "secondary"
                    }
                    className="daksh-transition"
                  >
                    {parcel.proactiveAlert.severity}
                  </Badge>
                </div>
                <div className="mt-2 text-xs text-muted-foreground">
                  Last updated: <span className="daksh-code">{parcel.proactiveAlert.updatedAt}</span>
                </div>
              </AlertDescription>
            </Alert>

            <Card className="daksh-glass daksh-elevated daksh-transition">
              <CardHeader className="space-y-2">
                <CardTitle className="flex flex-wrap items-center justify-between gap-2 text-base">
                  <span className="inline-flex items-center gap-2">
                    <Package className="h-4 w-4 text-primary" />
                    <span className="daksh-code">{parcel.trackingId}</span> • {parcel.articleType}
                  </span>
                  <Badge variant="secondary" className="daksh-transition">{parcel.currentStatusLabel}</Badge>
                </CardTitle>
                <div className="grid gap-2 text-sm text-muted-foreground sm:grid-cols-2">
                  <div className="rounded-md border daksh-glass bg-muted/20 p-3 daksh-elevated daksh-transition">
                    <div className="daksh-kicker">Origin (DIGIPIN)</div>
                    <div className="mt-1 font-medium text-foreground">{parcel.originCity}</div>
                    <div className="mt-1 daksh-code text-xs">{parcel.originDigipin}</div>
                  </div>
                  <div className="rounded-md border daksh-glass bg-muted/20 p-3 daksh-elevated daksh-transition">
                    <div className="daksh-kicker">Destination (DIGIPIN)</div>
                    <div className="mt-1 font-medium text-foreground">{parcel.destinationCity}</div>
                    <div className="mt-1 daksh-code text-xs">{parcel.destinationDigipin}</div>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="mb-4 flex items-center justify-between gap-3 rounded-md border daksh-glass bg-background p-3 daksh-elevated daksh-transition">
                  <div className="flex items-center gap-2 text-sm">
                    <MapPin className="h-4 w-4 text-primary" />
                    <span className="font-medium">Current hub:</span>
                    <span className="text-muted-foreground daksh-code">
                      {parcel.currentHub} ({parcel.currentHubCode})
                    </span>
                  </div>
                  <div className="text-xs text-muted-foreground">
                    Booked: <span className="daksh-code">{parcel.bookedAt}</span>
                  </div>
                </div>

                <ParcelTimeline events={parcel.timeline} />
              </CardContent>
            </Card>
          </div>

          <div className="space-y-6">
            <DelayPredictionCard prediction={parcel.prediction} />

            <Card className="daksh-glass daksh-elevated daksh-transition">
              <CardHeader>
                <CardTitle className="text-base">Operator Notes</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2 text-sm text-muted-foreground leading-relaxed">
                <p>
                  Predictions are shown as an explainable summary (probability + factors) to support
                  citizen trust and operator triage.
                </p>
                <p>
                  DIGIPIN codes are displayed consistently to improve address intelligence and reduce
                  last-mile ambiguity.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      )}
    </div>
  );
}
