// eCom/supabase/database.types.ts
// Database type definitions for Supabase
//
// NOTE: This file is typically generated by Supabase CLI using:
//   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > supabase/database.types.ts
//
// For now, this is a minimal stub to allow the build to pass.
// Replace this with the generated types for full type safety.

export type Database = {
  public: {
    Tables: Record<string, any>;
    Views: Record<string, any>;
    Functions: Record<string, any>;
    Enums: Record<string, any>;
  };
};
